#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=TrainGPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
cd $HOME/uvadlc_practicals_2024/assignment2/part2
# Activate your environment
source activate dl2024
# Run your code
srun python train.py --log_dir='./flash_logs' --use_flash_attn
srun python generate.py --model_weights_folder='./flash_logs/gpt-mini/version_0/checkpoints'